import 'package:country_info_flutter/providers/country_info_provider.dart';
import 'package:flutter/material.dart';
import 'package:flutter_riverpod/flutter_riverpod.dart';

class Languages extends ConsumerWidget {
  const Languages({super.key});

  @override
  Widget build(BuildContext context, WidgetRef ref) {
    // List of available languages
    final availableLanguages = [
      "Afrikaans",
      "Albanian",
      "Amharic",
      "Arabic",
      "Aramaic",
      "Armenian",
      "Aymara",
      "Azerbaijani",
      "Basque",
      "Belarusian",
      "Belizian Creole",
      "Bengali",
      "Berber",
      "Bislama",
      "Bosnian",
      "Bulgarian",
      "Burmese",
      "Carolinian",
      "Catalan",
      "Chamorro",
      "Chewa",
      "Chibarwe",
      "Chinese",
      "Comorian",
      "Cook Islands Māori",
      "Croatian",
      "Czech",
      "Danish",
      "Dari",
      "Dzongkha",
      "Dutch",
      "English",
      "Estonian",
      "Faroese",
      "Fijian",
      "Fiji Hindi",
      "Filipino",
      "Finnish",
      "French",
      "Spanish",
      "Galician",
      "Georgian",
      "German",
      "Swiss German",
      "Gilbertese",
      "Greek",
      "Greenlandic",
      "Guaraní",
      "Guernésiais",
      "Haitian Creole",
      "Hassaniya",
      "Hebrew",
      "Herero",
      "Hindi",
      "Hiri Motu",
      "Hungarian",
      "Icelandic",
      "Indonesian",
      "Irish",
      "Italian",
      "Jamaican Patois",
      "Japanese",
      "Jèrriais",
      "Kalanga",
      "Kazakh",
      "Khmer",
      "Khoisan",
      "Khoekhoe",
      "Kikongo",
      "Kinyarwanda",
      "Kirundi",
      "Korean",
      "Kwangali",
      "Kyrgyz",
      "Lao",
      "Latin",
      "Latvian",
      "Lingala",
      "Lithuanian",
      "Lozi",
      "Luxembourgish",
      "Macedonian",
      "Malagasy",
      "Malay",
      "Maldivian",
      "Maltese",
      "Manx",
      "Māori",
      "Marshallese",
      "Mauritian Creole",
      "Mongolian",
      "Montenegrin",
      "Nauru",
      "Ndau",
      "Nepali",
      "New Zealand Sign Language",
      "Northern Ndebele",
      "Southern Ndebele",
      "Ndonga",
      "Niuean",
      "Northern Sotho",
      "Southern Sotho",
      "Norfuk",
      "Norwegian",
      "Norwegian Bokmål",
      "Norwegian Nynorsk",
      "Palauan",
      "Papiamento",
      "Pashto",
      "Persian (Farsi)",
      "Polish",
      "Portoguese",
      "Quechua",
      "Romanian",
      "Romansh",
      "Russian",
      "Sami",
      "Samoan",
      "Sango",
      "Serbian",
      "Seychellois Creole",
      "Shona",
      "Sinhala",
      "Slovak",
      "Slovene",
      "Somali",
      "Sorani",
      "Sotho",
      "Spanish",
      "Swahili",
      "Swazi",
      "Swedish",
      "Tajik",
      "Tamil",
      "Tetum",
      "Thai",
      "Tigrinya",
      "Tokelauan",
      "Tok Pisin",
      "Tongan",
      "Tshiluba",
      "Tsonga",
      "Tswana",
      "Turkish",
      "Turkmen",
      "Tuvaluan",
      "Ukranian",
      "Upper Guinea Creole",
      "Urdu",
      "Uzbek",
      "Venda",
      "Vietnamese",
      "Xhosa",
      "Zimbabwean Sign Language",
      "Zulu"
    ];
    final selectedLanguage = ref.watch(selectedLanguageProvider);

    return SafeArea(
      child: Scaffold(
        appBar: AppBar(title: Text("Languages")),
        // Language Dropdown
        body: ListView.builder(
          shrinkWrap: true,
          itemCount: availableLanguages.length,
          itemBuilder: (context, index) {
            final language = availableLanguages[index];
            return RadioListTile.adaptive(
              title: Text(language),
              value: language,
              groupValue: selectedLanguage,
              onChanged: (value) {
                ref.read(selectedLanguageProvider.notifier).state = value;
                ref.invalidate(countriesProvider); // Clear previous data
                ref.read(filtersProvider.notifier).state =
                    ({"lang": language, "region": null});
                ref.read(countriesProvider);
                Navigator.of(context).pop();
              },
            );
          },
        ),
        // DropdownButton<String>(
        //   value: selectedLanguage,
        //   hint: Text("Select Language"),
        //   onChanged: (value) =>
        //       ref.read(selectedLanguageProvider.notifier).state = value,
        //   items: availableLanguages.map((lang) {
        //     return DropdownMenuItem(value: lang, child: Text(lang));
        //   }).toList(),
        // ),
      ),
    );
  }
}
